# Generated by Django 5.0 on 2024-12-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_rename_name_category_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='ads_images/'),
        ),
    ]
