# Generated by Django 5.1.4 on 2024-12-24 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_message_content_message_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message',
        ),
    ]
