# Generated by Django 4.2 on 2024-12-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_alter_advertisement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='shirt_size',
            field=models.CharField(choices=[('N', 'New'), ('as_new', 'as new'), ('U', 'Used')], default='N', max_length=6),
        ),
    ]
