# Generated by Django 5.1.4 on 2024-12-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_populate_room_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='token',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
