# Generated by Django 5.1.4 on 2025-01-15 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0017_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='Main.advertisement'),
        ),
    ]
