# Generated by Django 5.1.4 on 2025-01-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0018_alter_bookmark_advertisement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='token',
            field=models.CharField(blank=True, default='default_token', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
